config/routes.rb
Rails.application.routes.draw do

  resources :cats do
    resources :cat_rental_requests, except: [:index, :show]
  end

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = ["black", "white", "brown"]

  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :sex, inclusion: { in: ["M", "F"] }
  validates :color, inclusion: { in: COLORS }

  has_many :rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy

  def age
    (Time.now.to_i - birth_date.to_time.to_i) / (365 * 24 * 60 * 60)
  end

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: ['APPROVED', 'PENDING', 'DENIED']
  validate :does_not_overlap_approved_request

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat

  def overlapping_requests
    CatRentalRequest
      .where(cat_id: cat.id)
      .where(<<-SQL, start_date, end_date, id)
        NOT (? > end_date OR ? < start_date) AND id != ?
      SQL
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: "APPROVED")
  end

  def does_not_overlap_approved_request
    return if self.status == 'DENIED'
    if overlapping_approved_requests.exists?
      errors[:no_overlaps] << "Overlapping request"
    end
  end

  def approve!
    unless overlapping_approved_requests.exists?
      ActiveRecord::Base.transaction do
        self.status = 'APPROVED'
        save
        overlapping = []
        overlapping_requests.each {|request| overlapping << request}
        overlapping.each(&:deny!)
      end
    end
  end

  protected

  def deny!
    self.status = 'DENIED'
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @request = CatRentalRequest.new
    render :new
  end

  def create
    @request = CatRentalRequest.new(rental_params)
    @cat = Cat.find_by(id: rental_params[:cat_id])
    
    if @request.save
      redirect_to cat_url(@cat)
    else
      render :new
    end

  end

  private

  def rental_params
    params.require(:request).permit(:cat_id, :start_date, :end_date, :status)
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    @requests = @cat.rental_requests
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      redirect_to cats_url
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update_attributes(cat_params)
      render :show
    else
      redirect_to edit_cat_url(@cat)
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_request_helper.rb
module CatRentalRequestHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/_form.html.erb
<% if action == :new %>
  <% action_url = cat_cat_rental_requests_url %>
<% elsif action == :edit%>
  <% action_url = edit_cat_cat_rental_request_url(rental_cat, request) %> <!--Potential error -->
<% end %>

<% rental_cat = rental.cat || Cat.new %>

<form action="<%= action_url %>" method="post">
  <% if rental.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="cat_choice">Cat Choice:</label>
  <select id="cat_choice" name="request[cat_id]">
    <option disabled <%= 'selected' if action == :new %> >--Select color--</option>
    <% Cat.all.each do |cat| %>
      <option value="<%= cat.id %>" <%= cat.id == rental_cat.id ? 'selected' : "" %> > <%= cat.name %> </option>
    <% end %>
  </select>

  <br>

  <label for="start_date">Start Date</label>
  <input type="date" name="request[start_date]" value="<%rental.start_date%>">

  <br>

  <label for="end_date">End Date</label>
  <input type="date" name="request[end_date]" value="<%rental.end_date%>">

  <br><br>

  <input type="submit" value="<%= action.capitalize %>">

</form>

app/views/cat_rental_requests/edit.html.erb
<h1>Edit Rental Request</h1>

<%= render 'form', rental: @request, action: :edit %>

app/views/cat_rental_requests/new.html.erb
<h1>Input Rental Request</h1>

<%= render 'form', rental: @request, action: :new %>

app/views/cats/_form.html.erb
<% if action == :new %>
  <% action_url = cats_url %>
<% elsif action == :edit%>
  <% action_url = cat_url(cat) %>
<% end %>


<form action="<%= action_url %>" method="post">
  <% if cat.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%=cat.name%>">

  <br>

  <label for="birth_date">Birth Date</label>
  <input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">

  <br>

  <label>Sex
  M <input type="radio" name="cat[sex]" value="M" <%= cat.sex == 'M' ? 'checked' : "" %>>
  F <input type="radio" name="cat[sex]" value="F" <%= cat.sex == 'F' ? 'checked' : "" %>>
  </label>

  <br>

  <label for="color">Color Choice:</label>
  <select id="color" name="cat[color]">
    <option disabled>--Select color--</option>
    <% Cat::COLORS.each do |color| %>
      <option value="<%= color %>" <%= cat.color == color ? 'selected' : "" %> > <%= color.capitalize %> </option>
    <% end %>
  </select>

  <br><br>

  <textarea name="cat[description]" rows="8" cols="80">
    <%= cat.description %>
  </textarea>
  <br>

  <input type="submit" value="<%= action.capitalize %> cat">

</form>

<br><br>

<%= link_to 'Return', cats_url %>

app/views/cats/edit.html.erb
<h1>Edit Cat</h1>

<%= render 'form', cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<h1>Winber's Cats</h1>

<ul>
  <% @cats.each do |cat| %>
    <li><%= link_to cat.name, cat_url(cat) %></li>
  <% end %>
</ul>

<%= link_to 'Add Cat', new_cat_url %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form', cat: @cat, action: :new %>

app/views/cats/show.html.erb
<h1> <%= @cat.name %> </h1>
<table>
    <thead>
      <tr>
        <th>Attribute</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Age</td>
        <td> <%= @cat.age %> </td>
      </tr>
      <tr>
        <td>Color</td>
        <td> <%= @cat.color %> </td>
      </tr>
      <tr>
        <td>Name</td>
        <td> <%= @cat.name %> </td>
      </tr>
      <tr>
        <td>Sex</td>
        <td> <%= @cat.sex %> </td>
      </tr>
    </tbody>
</table>
<p><%= @cat.description %></p>
<table>
    <thead>
      <tr>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Status</th>
        <!-- <th>Approve Button </th> -->
      </tr>
    </thead>
    <tbody>
        <% @requests.order(:start_date).each do |request| %>
        <% next unless request.status == 'APPROVED' %>
        <tr>
          <td><%=request.start_date%></td>
          <td><%=request.end_date%></td>
          <td><%=request.status%></td>
          <!-- <td><%#=button_to 'Approve?', action: request.approve%></td> -->
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'Return', cats_url %>
<br>
<%= link_to 'New Request', new_cat_cat_rental_request_url(@cat) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyProjectName</title>
  <!-- <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %> -->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>